#!/bin/bash
# Made by Joy

echo "Installing Pterodactyl Panel with Docker..."

# Step 1: Create directory structure
mkdir -p pterodactyl/panel
cd pterodactyl/panel || exit

# Step 2: Create docker-compose.yml file
cat <<EOF > docker-compose.yml
version: '3.8'

x-common:
  database:
    MYSQL_PASSWORD: &db-password "CHANGE_ME"

  &db-environment
  MYSQL_ROOT_PASSWORD: "CHANGE_ME_TOO"

panel:
  &panel-environment
  APP_URL: "https://pterodactyl.example.com"
  APP TIMEZONE: "UTC"
  APP_SERVICE_AUTHOR: "noreply@example.com"
  TRUSTED PROXIES: "*"

mail:
  &mail-environment
  MAIL_FROM: "noreply@example.com"
  MAIL DRIVER: "smtp"
  MAIL HOST: "mail"
  MAIL_PORT: "1025"
  MAIL USERNAME:
  MAIL PASSWORD:
  MAIL_ENCRYPTION: "true"

services:
  database:
    image: mariadb:10.5
    restart: always
    command: --default-authentication-plugin=mysql_native_password

    volumes:
      - "/srv/pterodactyl/database:/var/lib/mysql"

    environment:
      <<: *db-environment
      MYSQL DATABASE: "panel"
      MYSQL_USER: "pterodactyl"

  cache:
    image: redis:alpine
    restart: always

  panel:
    image: ghcr.io/pterodactyl/panel:latest
    restart: always

    ports:
      - "80:80"
      - "443:443"

    links:
      - database
      - cache

    volumes:
      - "/srv/pterodactyl/var/:/app/var/"
      - "/srv/pterodactyl/nginx/:/etc/nginx/http.d/"
      - "/srv/pterodactyl/certs/:/etc/letsencrypt/"
      - "/srv/pterodactyl/logs/:/app/storage/logs"

    environment:
      <<: [*panel-environment, *mail-environment]
      DB_PASSWORD: *db-password
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      DB_HOST: "database"
      DB_PORT: "3306"

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
EOF

# Step 3: Start Docker containers
docker-compose up -d

echo "Pterodactyl Panel installation complete!"
echo "Access your panel at: http://localhost or your-server-ip"
echo "Access your panel at port 80: http://localhost:80 or your-server-ip:80"

# Step 4: Create an admin user for the Panel
docker-compose run --rm panel php artisan p:user:make
